version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: server_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: server
    ports:
      - "5442:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: server_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
